repos:
  - repo: local
    hooks:
      - id: collect-context
        name: collect-context
        entry: scripts/precommit_run_collect_context.sh
        language: script
        stages: [pre-commit]
        always_run: false
        require_serial: true
        pass_filenames: false
        files: ''
      - id: generate-beads-backlog
        name: generate-beads-backlog
        entry: python3 scripts/generate_beads_backlog.py
        language: system
        stages: [pre-commit]
        always_run: true
        require_serial: true
        pass_filenames: false
        files: ''
