#!/bin/bash
# Generate BuildInfo.swift with current timestamp

VERSION="1.0.0"
# Format: YYYYMMDD.HHMM (UTC) - seconds removed for stability
BUILD_ID=$(date -u +"%Y%m%d.%H%M")

cat > "$1" << EOF
// This file is automatically generated. Do not edit.

import Foundation

public enum BuildInfo {
    public static let version = "$VERSION"
    public static let buildID = "$BUILD_ID"
    public static let versionWithBuildID = "$VERSION+$BUILD_ID"
}
EOF

echo "Generated BuildInfo.swift with version $VERSION+$BUILD_ID (format YYYYMMDD.HHMM)"
