import Foundation
@_spi(Generated) import OpenAPIRuntime

/// Public API for registering handlers
extension APIHandler {
    /// Register this handler's operations with a transport.
    ///
    /// This is a public wrapper around the internal registerHandlers method
    /// generated by the OpenAPI generator.
    public func register(on transport: any ServerTransport) throws {
        try registerHandlers(on: transport)
    }
}
